version: 2
updates:
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "weekly"
        groups:
            github-actions:
                applies-to: version-updates
                patterns:
                    - "*"
            github-actions-minor-and-patch:
                applies-to: security-updates
                patterns:
                    - "*"
    -   package-ecosystem: "gradle"
        directory: "/"
        schedule:
            interval: "weekly"
