name: 'Setup environment for the build'

inputs:
    cache-disabled:
        description: 'gradle.cache-disabled'
        default: 'false'
    cache-read-only:
        description: 'gradle.cache-read-only'
        default: 'true'

env:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

runs:
    using: 'composite'
    steps:
        -   name: Configure JDK 8
            uses: actions/setup-java@v4
            with:
                distribution: ${{ (runner.os == 'macOS' && runner.arch == 'ARM64') && 'zulu' || 'temurin' }}
                java-version: 8

        -   name: Configure JDK
            uses: actions/setup-java@v4
            with:
                distribution: 'zulu'
                java-version: 17

        -   name: Cache Gradle Dependencies
            uses: actions/cache@v4
            with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ matrix.os }}-gradle-${{ hashFiles('gradle/catalogs/*.versions.toml') }}
                enableCrossOsArchive: true

        -   name: make Gradlew executable
            if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
            run: |
                chmod 755 ./gradlew
            shell: "bash"

        -   name: Validate Gradle wrapper
            uses: gradle/actions/wrapper-validation@v3

        -   uses: gradle/actions/setup-gradle@v4
            with:
                cache-disabled: ${{ inputs.cache-disabled }}
                cache-read-only: ${{ inputs.cache-read-only }}

        -   if: runner.os == 'Windows'
            uses: msys2/setup-msys2@v2
            with:
                release: false
                install: mingw-w64-x86_64-openssl
