name: CI Main

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - "**.md"
            - ".idea/**"
            - ".editorconfig"
            - ".gitignore"

jobs:
    checks:
        uses: ./.github/workflows/run-checks.yml
