name: CI Main

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - "**.md"
            - ".idea/**"
            - ".editorconfig"
            - ".gitignore"

concurrency:
    group: ci-main-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    checks:
        uses: ./.github/workflows/run-checks.yml
